name: Build and test

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs:
  build-and-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and test
      run: dotnet fake build -t runTests

  build-and-test-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'
    - name: Restore local tools
      run: dotnet tool restore
    - name: Build and test
      run: dotnet fake build -t runTestsWithCodeCov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./
        files: ./codeCov.txt
        verbose: true
